<?php
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Queue\QueueFactory;
use Drupal\Core\Queue\QueueInterface;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Session\AccountInterface;
use Drupal\node\NodeInterface;
use Drupal\Core\Node;

/**
* Implements hook_entity_insert().
*/
function starwars_theme($existing, $type, $theme, $path){
  return [
    'starwars_template' => [
      'variables' => ['message' => NULL],
    ],
  ];
}

function starwars_cron() {
  $result = \Drupal::service('starwars.sources');
  $queue_factory = \Drupal::service('queue');
  $queue = $queue_factory->get('cron_node');
  $apiUrl = $result->getUrl();
  $lastUpdateTime = \Drupal::state()->get('edit');
  if(!isset($lastUpdateTime)){
    $lastUpdateTime = 0;
  }
  foreach ($apiUrl as $key => $item) {
    $data = [
      'type' => $key,
      'url' => $item,
      'lastUpdate' => $lastUpdateTime,
    ];
    $queue->createItem($data);
  }
  \Drupal::state()->set('edit',$_SERVER['REQUEST_TIME']);
}

function starwars_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if($form_id == "contact_message_starwars_form_form"){
    $user = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
    $form['field_name']['widget']['0']['#default_value'] = $user->field_name->value;
    $form['field_surname']['widget']['0']['#default_value'] = $user->field_surname->value;
  }
  if($form_id == "views_exposed_form"){
    $form['actions']['reset']['#access'] = TRUE;
  }
  if($form_id == "starwars_ajax") {
    $form['#attached']['library'][] = 'starwars/starwars_ajax_command';
  }
}
function batch_process_items($date,$console, &$context){
  define('LIMIT', '2');
  $serviceApi = \Drupal::service('starwars.sources');
  $apiUrl = $serviceApi->getUrl();
  if(empty($context['sandbox']['link'])){
    $context['sandbox']['progress'] = 0;
    $context['sandbox']['link'] = current($apiUrl);
    $context['sandbox']['type'] = array_key_first($apiUrl);
  }
  $context['finished'] = 0;
  if(empty($context['sandbox']['data'])){
    $result = $serviceApi->getApiByUrl($context['sandbox']['link']);
    $context['sandbox']['data'] = $result;
  }else{
    $result = $context['sandbox']['data'];
  }
  $type = $context['sandbox']['type'];
  $counter = 0;
  $countLimit = 0;
  foreach ($result->results as $item) {
    if($countLimit<$context['sandbox']['limit']){
      $countLimit++;
      continue;
    }
    if($counter != LIMIT){
      $counter++;
      $edit = strtotime($item->edited);
      $context['sandbox']['progress']++;
      if ($edit >= $date) {
        $item->type = $type;
        batch_process_item($item);
      }
    if(PHP_SAPI === 'cli') {

    }else{
      $context['message'] = t('Now processing node :progress', [
        ':progress' => $context['sandbox']['progress'],
      ]);
    }
    }else{
      break;
    }
  }
  $context['sandbox']['limit'] += $counter;
  if($context['sandbox']['limit'] == count($result->results)){
    $context['sandbox']['limit'] = 0;
    unset($context['sandbox']['data']);
    if(isset($result->next)){
      $context['sandbox']['link'] = $result->next;
    }else{
      if($serviceApi->nextTypeLink($type)){
        $data = $serviceApi->nextTypeLink($type);
        $context['sandbox']['link'] = $data['link'];
        $context['sandbox']['type'] = $data['type'];
      }else{
        $context['finished'] = 1;
      }
    }
  }
  $context['results']['processed'] = $context['sandbox']['progress'];

}
/*
function batch_process_items2($date,$console, &$context){
  define('LIMIT', '2');
  $context['results']['console'] = $console;
  $context['finished'] = 0;
  $serviceApi = \Drupal::service('starwars.sources');
  $apiUrl = $serviceApi->getUrl();
  $count = count($apiUrl);
  $percnet = 1/$count;
  if (empty($context['sandbox']['progress'])) {
    $context['sandbox']['progress'] = 0;
    $context['sandbox']['link'] = current($apiUrl);
    $context['sandbox']['type'] = 0;
  }
  $counter = 0;
  $result = $serviceApi->getApiByUrl($context['sandbox']['link']);
  $keys = array_keys($apiUrl);
  $type = $keys[$context['sandbox']['type']];
  if(isset($result->next)){
    $context['sandbox']['link'] = $result->next;
  }else{
    $context['sandbox']['type']++;
    $context['finished'] += $percnet;
    if($context['sandbox']['type'] == $count){
      $context['finished'] = 1;
    }else{
      $typenext = $keys[$context['sandbox']['type']];
      $context['sandbox']['link'] = $apiUrl[$typenext];
    }
  }
  $maxCount = count($result->results);
  foreach ($result->results as $item){
    if($counter < $context['sandbox']['limit']){
      continue;
    }
    if ($counter != LIMIT) {
      $edit = strtotime($item->edited);
      $context['sandbox']['progress']++;
      $counter++;
      if ($edit >= $date) {
        $item->type = $type;
        batch_process_item($item);
      }
      if($console){
// drupal is clear
      } else {
        $context['message'] = t('Now processing node :progress', [
          ':progress' => $context['sandbox']['progress'],
        ]);
      }
      $context['results']['processed'] = $context['sandbox']['progress'];
    }else{
      $context['sandbox']['limit'] += $counter;
      break;
    }
  }
  if($context['sandbox']['limit'] == $maxCount){
    $context['sandbox']['limit'] = 0;
  }
}
*/
function batch_process_item($item){
  $serviceApi = \Drupal::service('starwars.batch');
  $serviceApi->createNode($item);
}

function batch_starwars_finished($success, $results, $operations) {
  if (PHP_SAPI === 'cli') {
   print('Number of nodes affected by batch:' . $results['processed']);
  } else {
    $message = t('Number of nodes affected by batch: @count', [
      '@count' => $results['processed'],
    ]);
    \Drupal::messenger()
      ->addStatus($message);
  }
}

function starwars_node_access(NodeInterface $node, $op, AccountInterface $account) {
  $type = $node->bundle();
if($type === 'people') {
  $roles = $account->getRoles();
  switch ($op) {
    case 'create':
      $access = AccessResult::allowedIfHasPermission($account, 'create ' . $type . ' content');
      break;
    case 'update':
      $access = AccessResult::allowedIfHasPermission($account, 'update any ' . $type . ' content');
      if(array_search('editor',$roles)) {
        $editors = $node->get('field_editor')->getValue();
        $access = AccessResult::forbidden();
        if (!empty($editors)) {
          foreach ($editors as $item) {
            if (array_search($account->id(), $item)) {
              $access = AccessResult::allowed();
              break;
            }
          }
        }
      }
      break;

    case 'delete':
      $access = AccessResult::allowedIfHasPermission($account, 'delete any ' . $type . ' content');
      if (!$access->isAllowed() && $account->hasPermission('delete own ' . $type . ' content')) {
        $access = $access->orIf(AccessResult::allowedIf($account->id() == $node->getOwnerId()))->cachePerUser()->addCacheableDependency($node);
      }
      break;

    default:
      $access = AccessResult::neutral();
  }

  return $access;
}
}

function starwars_entity_field_access($operation, \Drupal\Core\Field\FieldDefinitionInterface $field_definition, \Drupal\Core\Session\AccountInterface $account, \Drupal\Core\Field\FieldItemListInterface $items = NULL) {

  $fields_names = array(
    'field_editor'
  );

  if (in_array($field_definition->getName(), $fields_names)) {
    $account = \Drupal::currentUser();
    if (in_array('editor', $account->getRoles())) {
      return AccessResult::forbidden();
    }
  }

  return AccessResult::neutral();
}
function starwars_node_insert($node)
{
  if ($node->bundle() === 'people') {
  $user = \Drupal::currentUser();
  $roles = $user->getRoles();
  if (in_array('editor', $roles)) {
    $node->set('field_editor', $user->id());
    $node->save();
  }
}
}


